title: Cristian Tobar
logo: /assets/profile.png
description: I am a Data Scientist, Machine Learning Researcher and PhD Candidate from Colombia ðŸ‡¨ðŸ‡´. e-mail/cristiantobarov@gmail.com
#show_downloads: true 
theme: jekyll-theme-minimal
